#!/bin/bash

# https://github.com/abusenius/insaned/blob/master/events/copy

# Samsung_ML-2525W_Series

source /etc/scanbd/scripts/functions

create_lock

TMPFILE="/tmp/copy.tiff"

scanimage --format tiff --mode Gray \
    -l 2 -t 0 -x 206 -y 293 --resolution 300 --contrast 18 --brightness 4 --swdespeck=yes --despeck 3 > $TMPFILE

tiff2ps -c -w 8.11 -h 11.54 $TMPFILE | lpr -P Samsung_ML-2525W_Series

rm -f $TMPFILE

remove_lock
